# =====================
FROM node:alpine AS build-dev

WORKDIR /app-dev

COPY package.json package.json
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-dev /app-dev/build /usr/share/nginx/html
COPY --from=build-dev /app-dev/nginx/rsp.conf /etc/nginx/sites-available/rsp.conf

EXPOSE 3000
CMD [ "nginx", "-g", "daemon off;" ]