# =====================
FROM node:alpine AS build-prod

WORKDIR /app-prod

COPY package.json package.json
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-prod /app-prod/build /usr/share/nginx/html
COPY --from=build-prod /app-prod/nginx/rsp.conf /etc/nginx/sites-available/rsp.conf

EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]